name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Tests
      run: dotnet test

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Install tools
      run: |
        dotnet tool install -g dotnet-format
        dotnet tool install -g roslynator.dotnet.cli

    - name: Run dotnet format
      run: dotnet format --verify-no-changes

    - name: Run roslynator analyze
      run: roslynator analyze --severity-level warning
