name: .NET

on: 
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
            
    - name: Publish Windows
      run: dotnet publish -r win-x64 -c Release -p:Version=${{ github.REF.NAME }} --no-self-contained -o output/win-x64
      
    - name: Publish Linux
      run: dotnet publish -r linux-x64 -c Release -p:Version=${{ github.REF.NAME }} --no-self-contained  -o output/linux-x64
      
    - name: Create Release
      uses: ncipollo/release-action@v1.8.10
      with:
        artifacts: "output/*"
        name: 'v${{ github.REF.NAME }}'
        tag: ${{ github.REF.NAME }}
        draft: true
        commit: ${{ github.SHA }}
